<?php
/**
 * User: Tom Etzel
 * Date: 5/22/2014
 * Time: 10:38 PM
 */

$title = 'Available Entities';
$this->headTitle($title);
?>
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <h1><?php echo $this->escapeHtml($title); ?></h1>

            <table class="table">
                <tr>
                    <th>Entity Name</th>
                    <th>Actions</th>
                </tr>
                <?php foreach($entities as $entity) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($entity['name']); ?></td>
                        <td>
                            <a href="<?php echo "#";//$this->url('Admin\book', array('action'=>'edit', 'id'=>$book->id));?>">Generate CRUD</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div> 